[package]
name = "tear"
version = "0.1.0"
authors = ["Sam Lakerveld <darkwater124@gmail.com>"]

[dependencies]
input       = "^0.1.1"
libudev-sys = "^0.1.3"
config      = "^0.4"
libc        = "^0.2.23"
